;; seed: 620
(define (domain rover)
(:requirements :typing :durative-actions)
 (:types
 lander waypoint store camera mode rover objective - object
 )
(:predicates
 (at ?a - rover ?b - waypoint)
 (at_lander ?a - lander ?b - waypoint)
 (can_traverse ?a - rover ?b - waypoint ?c - waypoint)
 (equipped_for_soil_analysis ?a - rover)
 (equipped_for_rock_analysis ?a - rover)
 (equipped_for_imaging ?a - rover)
 (empty ?a - store)
 (have_rock_analysis ?a - rover ?b - waypoint)
 (have_soil_analysis ?a - rover ?b - waypoint)
 (full ?a - store)
 (calibrated ?a - camera ?b - rover)
 (supports ?a - camera ?b - mode)
 (available ?a - rover)
 (visible ?a - waypoint ?b - waypoint)
 (have_image ?a - rover ?b - objective ?c - mode)
 (communicated_soil_data ?a - waypoint)
 (communicated_rock_data ?a - waypoint)
 (communicated_image_data ?a - objective ?b - mode)
 (at_soil_sample ?a - waypoint)
 (at_rock_sample ?a - waypoint)
 (visible_from ?a - objective ?b - waypoint)
 (store_of ?a - store ?b - rover)
 (calibration_target ?a - camera ?b - objective)
 (on_board ?a - camera ?b - rover)
 (channel_free ?a - lander)
 (is-true))
 
(:action navigate
:parameters (?x - rover ?y - waypoint ?z - waypoint)
:cost (navigate-cost ?y ?z)
:precondition (and 
(can_traverse ?x ?y ?z)
(available ?x)
(at ?x ?y)
(visible ?y ?z)
)
:effect (and
(not (at ?x ?y))
(at ?x ?z)
)
)
(:action sample_soil
:parameters (?x - rover ?s - store ?p - waypoint)
:cost (soil-cost ?s ?p)
:precondition (and 
(at ?x ?p)
(at_soil_sample ?p)
(equipped_for_soil_analysis ?x)
(store_of ?s ?x)
(empty ?s)
)
:effect (and
(not (empty ?s))
(full ?s)
(have_soil_analysis ?x ?p)
(not (at_soil_sample ?p))
)
)
(:action sample_rock
:parameters (?x - rover ?s - store ?p - waypoint)
:cost (rock-cost ?s ?p)
:precondition (and 
(at ?x ?p)
(at_rock_sample ?p)
(equipped_for_rock_analysis ?x)
(store_of ?s ?x)
(empty ?s)
)
:effect (and
(not (empty ?s))
(full ?s)
(have_rock_analysis ?x ?p)
(not (at_rock_sample ?p))
)
)
(:action drop
:parameters (?x - rover ?y - store)
:cost (drop-cost ?y)
:precondition (and 
(store_of ?y ?x)
(full ?y)
)
:effect (and
(not (full ?y))
(empty ?y)
)
)
(:action calibrate
:parameters (?r - rover ?i - camera ?t - objective ?w - waypoint)
:cost (calibrate-cost ?i)
:precondition (and 
(equipped_for_imaging ?r)
(calibration_target ?i ?t)
(at ?r ?w)
(visible_from ?t ?w)
(on_board ?i ?r)
)
:effect (and
(calibrated ?i ?r)
)
)
(:action take_image
:parameters (?r - rover ?p - waypoint ?o - objective ?i - camera ?m - mode)
:cost (image-cost ?i)
:precondition (and 
(calibrated ?i ?r)
(on_board ?i ?r)
(equipped_for_imaging ?r)
(supports ?i ?m)
(visible_from ?o ?p)
(at ?r ?p)
)
:effect (and
(have_image ?r ?o ?m)
(not (calibrated ?i ?r))
)
)
(:action communicate_soil_data
:parameters (?r - rover ?l - lander ?p - waypoint ?x - waypoint ?y - waypoint)
:cost (soil-comm-cost ?r)
:precondition (and 
(at ?r ?x)
(at_lander ?l ?y)
(have_soil_analysis ?r ?p)
(visible ?x ?y)
(available ?r)
(channel_free ?l)
)
:effect (and
(channel_free ?l)
(communicated_soil_data ?p)
(available ?r)
)
)
(:action communicate_rock_data
:parameters (?r - rover ?l - lander ?p - waypoint ?x - waypoint ?y - waypoint)
:cost (rock-comm-cost ?r)
:precondition (and 
(at ?r ?x)
(at_lander ?l ?y)
(have_rock_analysis ?r ?p)
(visible ?x ?y)
(available ?r)
(channel_free ?l)
)
:effect (and
(channel_free ?l)
(communicated_rock_data ?p)
(available ?r)
)
)
(:action communicate_image_data
:parameters (?r - rover ?l - lander ?o - objective ?m - mode ?x - waypoint ?y - waypoint)
:cost (image-comm-cost ?r)
:precondition (and 
(at ?r ?x)
(at_lander ?l ?y)
(have_image ?r ?o ?m)
(visible ?x ?y)
(available ?r)
(channel_free ?l)
)
:effect (and
(channel_free ?l)
(communicated_image_data ?o ?m)
(available ?r)
)
))
